# Dovecot — LMTP (20-lmtp.conf)

# От этого адреса Dovecot генерирует ответы об отпуске/ошибках sieve
postmaster_address = postmaster@mymyblog.cf

hostname = mail.mymyblog.cf

protocol lmtp {
  # Sieve-фильтрация при доставке (пакет dovecot-sieve)
  mail_plugins = $mail_plugins sieve
}
